// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompanyRegistrationNumberController from "./company_registration_number_controller"
application.register("company-registration-number", CompanyRegistrationNumberController)

import MoneyController from "./money_controller"
application.register("money", MoneyController)

import NumbersOnlyController from "./numbers_only_controller"
application.register("numbers-only", NumbersOnlyController)

import PhoneController from "./phone_controller"
application.register("phone", PhoneController)

import ShowhideController from "./showhide_controller"
application.register("showhide", ShowhideController)

import SocialSecurityNumberController from "./social_security_number_controller"
application.register("social-security-number", SocialSecurityNumberController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import ZipCodeController from "./zip_code_controller"
application.register("zip-code", ZipCodeController)
